# frozen_string_literal: true

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: root

development:
  primary:
    <<: *default
    database: voting_system_api_development
  queue:
    <<: *default
    database: voting_system_api_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: voting_system_api_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: voting_system_api_test

production:
  primary: &primary_production
    <<: *default
    database: voting_system_api_production
    username: voting_system_api
    password: <%= ENV["VOTING_SYSTEM_API_DATABASE_PASSWORD"] %>

  queue:
    <<: *primary_production
    database: voting_system_api_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: voting_system_api_production_cable
    migrations_paths: db/cable_migrate
